name: PR Title Validation
description: Validate that the title conforms to the conventional commit standards
author: Ruan de Villiers

# Define your inputs here.
inputs:
  pr-title:
    description: What is the title of the PR?
    required: true
    default: Hello
  regex:
    description: What regex should we use to validate the title?
    required: true
    default: "^[a-z]+-[0-9]+: .*"

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js